apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-api
spec:
  selector:
    matchLabels:
      app: playlist-api
  template:
    metadata:
      labels:
        app: playlist-api
    spec:
      containers:
      - name: playlist-api
        image: callspadeoz123/playlist-api-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env: 
        - name: MONGO_USERNAME
          valueFrom: 
            secretKeyRef:
              name: MONGO_USERNAME
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: MONGO_PASSWORD
              key: MONGO_PASSWORD
