apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-api
spec:
  selector:
    matchLabels:
      app: playlist-api
  template:
    metadata:
      labels:
        app: playlist-api
    spec:
      containers:
      - name: playlist-api
        image: callspadeoz123/playlist-api-image:latest
        ports:
        - containerPort: 5000
        env: 
        - name: MONGO_USERNAME
          valueFrom: 
            secretKeyRef:
              name: playlist-api-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: playlist-api-secret
              key: MONGO_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
spec:
  selector:
    app: playlist-api
  ports:
  - port: 5000
    targetPort: 5000
