apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-api-deployment
spec:
  selector:
    matchLabels:
      app: videos-api
  template:
    metadata:
      labels:
        app: videos-api
    spec:
      containers:
      - name: vidoes-api-deployment
        image: callspadeoz123/videos-api-image:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
        envFrom:
            - configMapRef:
                name: videos-api-configmap
            

         


---
apiVersion: v1
kind: Service
metadata:
  name: videos-api-service
spec:
  selector:
    app: videos-api
  ports:
  - port: 5001
    targetPort: 5001
