name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  pre-build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Echo tree
        run: tree
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker video-api-image
      run: docker build -t video-api-image:$(date +%s) --file ./videos-api/Dockerfile

    - name: Build Docker playlist-api-image
      run: docker build -t playlist-api-image:$(date +%s) --file ./playlist-api/Dockerfile

    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker video-api-image to Docker Hub
      run: docker push video-api-image
    
    - name: Push Docker playlist-api-image to Docker Hub
      run: docker push playlist-api-image