name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  pre-build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Echo tree
        run: tree
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build docker playlist-api-image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: playlist-api/ 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/playlist-api-image:$(date +%s)

    - name: Build docker video-api-image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: videos-api/ 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/video-api-image:$(date +%s)