name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  pre-build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Echo tree
        run: tree
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build Docker db-setup-image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/db-setup-image:latest db_setup/

      - name: Build Docker playlist-api-image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/playlist-api-image:latest playlist-api/
      
      - name: Build Docker video-api-image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/videos-api-image:latest videos-api/
  
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Push Docker  db-setup-image:latest to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/db-setup-image:latest

        - name: Push Docker playlist-api-image:latest to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/playlist-api-image:latest

      - name: Push Docker videos-api-image:latest to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/videos-api-image:latest
      