name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  pre-build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Echo tree
        run: tree
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build Docker playlist-api-image
        run: docker build -t playlist-api-image:latest -f playlist-api/
      
      - name: Build Docker video-api-image
        run: docker build -t video-api-image:latest -f videos-api/
  
      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  
      - name: Push Docker playlist-api-image:latest to Docker Hub
        run: docker push playlist-api-image:latest

      - name: Push Docker videos-api-image:latest to Docker Hub
        run: docker push videos-api-image:latest
      